version: "3"
services:
  app:
    build: 
      context: ./src/
      dockerfile: Dockerfile
    # links:
    #   - db
    depends_on:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql:latest
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat-app-db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
